POST https://bookifyserver.cyclic.cloud/register/
Content-Type: application/json

{
  "username": "Anuja",
  "password": "anuja123",
  "name": "Anuja",
  "gender": "female",
  "userId": 1
}
###
POST https://bookifyserver.cyclic.cloud/login/
Content-Type: application/json

{
  "username":"Anuja",
  "password":"anuja123"
}
###

###
POST https://bookifybackend.vercel.app/login/
Content-Type: application/json

{
  "username":"Anuja",
  "password":"anuja123"
}
###
POST https://bookifybackend.vercel.app/bookitem/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFudWphIiwiaWF0IjoxNjkwMzU2MTQ4fQ.Hpv6qYSpIFWXlr42T9jUVM25uqU6vU9u8GNXa9jqusw

{
    "bookId": 1,
    "title": "Hello",
    "authors": "Rose",
    "rating": "4",
    "reviewCount": "500",
    "ratingCount": "5000",
    "imageUrl": "https://res.cloudinary.com/dgkw0cxnh/image/upload/v1690355531/Book1_yn60zj.jpg"
}
###
GET https://bookifybackend.vercel.app/books/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFudWphIiwiaWF0IjoxNjkwMzU2MTQ4fQ.Hpv6qYSpIFWXlr42T9jUVM25uqU6vU9u8GNXa9jqusw
###
DELETE  https://bookifybackend.vercel.app/books/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFudWphIiwiaWF0IjoxNjkwMzU2MTQ4fQ.Hpv6qYSpIFWXlr42T9jUVM25uqU6vU9u8GNXa9jqusw
###